manager:
  image: galeb/galeb-manager
  ports:
   - "8000:8000"
  volumes:
   - ~/.m2:/home/galeb/.m2
  links:
   - db
   - redis

db:
    image: mysql:5.6
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=galeb

redis:
    image: redis:2.8

manager_webui:
  image: galeb/galeb-manager-webui
  links:
  - manager

router:
  image: galeb/galeb-router
  ports:
   - "8080:8080"
  volumes:
   - ~/docker/.m2:/home/galeb/.m2
  environment:
   - CLUSTER_ID=dev
   - VERSION=3.1.9-SNAPSHOT

api: 
  image: galeb/galeb-api
  ports:
   - "9090:9090"
  volumes:
   - ~/docker/.m2:/home/galeb/.m2
  environment:
   - CLUSTER_ID=dev
   - VERSION=3.1.9-SNAPSHOT

healthchecker:
  image: galeb/galeb-healthchecker
  volumes:
   - ~/docker/.m2:/home/galeb/.m2
  environment:
   - CLUSTER_ID=dev
   - VERSION=3.1.9-SNAPSHOT

backend1:
  image: galeb/backend-galeb-test
  ports:
   - "8081:8081"

backend2:
  image: galeb/backend-galeb-test
  ports:
   - "8082:8082"

backend3:
  image: galeb/backend-galeb-test
  ports:
   - "8083:8083"

backend4:
  image: galeb/backend-galeb-test
  ports:
   - "8084:8084"
